# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript



trigger:
- main

pool:
  default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm install'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'front-testing'
    organization: 'tatianasanchez1'
    scannerMode: 'MSBuild'
    projectKey: 'gestion-notas-front1'
    projectName: 'gestion-notas-front1'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm run build'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'